// ======= DO NOT EDIT THIS FILE ============
class Castor {
  String maker;
  int type,radius;
  Castor() {
   }
  Castor(String xMaker, int xType, int xRadius){
    maker=xMaker;type=xType; radius=xRadius;
   }
  @Override
  public String toString(){
    return("(" +maker+","+type + "," + radius + ")");
   }
 }
