// ======= DO NOT EDIT THIS FILE ============

class Node {

    Corn info;
    Node next;

    Node(Corn x, Node p) {
        info = x;
        next = p;
    }

    Node(Corn x) {
        this(x, null);
    }

    Node() {
    }
}
