// ======= DO NOT EDIT THIS FILE ============
class Bean{String code;
  int type,price;
  Bean() {
   }
  Bean(String xCode, int xType, int xPrice){
    code=xCode;type=xType; price=xPrice;
   }
  public String toString(){
    return("(" +code+","+type + "," + price + ")");
   }
 }
