// ======= DO NOT EDIT THIS FILE ============

class Node {

    Boat info;
    Node left, right;
    int bal, level;

    Node(Boat x) {
        info = x;
        left = right = null;
    }
}
