// ======= DO NOT EDIT THIS FILE ============
class Castor {
  String place;
  int depth,weight;
  Castor() {
   }
  Castor(String xMaker, int xType, int xRadius){
    place=xMaker;depth=xType; weight=xRadius;
   }
  public String toString(){
    return("(" +place+","+depth + "," + weight + ")");
   }
 }
