// Do not edit this file

class Node {

    Table info;
    Node next;

    Node(Table x, Node p) {
        info = x;
        next = p;
    }

    Node(Table x) {
        this(x, null);
    }
}
